name: deploy-example01
env:
  #
  # gh settings
  CI: true
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  #
  # c8y settings
  C8Y_SETTINGS_CI: true

on:
  workflow_dispatch:
    inputs:
      cli_options:
        description: 'Optional CLI arguments to be added to call'
        required: false
        default: ''

  release:
    types: [released]  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Manually download
          gh release download -R reubenmiller/go-c8y-cli --pattern c8y_linux_amd64 --dir "$HOME/.local/bin"
          mv "$HOME/.local/bin/c8y_linux_amd64" "$HOME/.local/bin/c8y"
          chmod +x "$HOME/.local/bin/c8y"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

          # Using homewbrew
          #brew tap reubenmiller/go-c8y-cli
          #brew update
          #brew install go-c8y-cli

      - name: Deploy web applications
        run: |
          chmod +x ./2022-01-27/02-cicd/deploy-webapps.sh
          ./2022-01-27/02-cicd/deploy-webapps.sh
        env:
          C8Y_HOST: ${{ secrets.C8Y_HOST }}
          # Tenant name is optional
          # C8Y_TENANT: ${{ secrets.C8Y_TENANT }}
          C8Y_USERNAME: ${{ secrets.C8Y_USERNAME }}
          C8Y_PASSWORD: ${{ secrets.C8Y_PASSWORD }}
