name: deploy-example01
env:
  CI: true
  C8Y_SETTINGS_CI: true

on:
  workflow_dispatch:
    inputs:
      cli_options:
        description: 'Optional CLI arguments to be added to call'
        required: false
        default: ''

  release:
    types: [released]  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dep
        run: |
          gh release download -R reubenmiller/go-c8y-cli --pattern c8y_linux_amd64 --dir $HOME/.local/bin
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          
          #brew tap reubenmiller/go-c8y-cli
          #brew update
          #brew install go-c8y-cli

      - name: Deploy web applications
        run: |
          ./2022-01-27/02-cicd/deploy-webapps.sh
        env:
          C8Y_HOST: ${{ secrets.C8Y_HOST }}
          C8Y_TENANT: ${{ secrets.C8Y_TENANT }}
          C8Y_USER: ${{ secrets.C8Y_USER }}
          C8Y_PASSWORD: ${{ secrets.C8Y_PASSWORD }}
