name: deploy-example02
env:
  #
  # gh settings
  CI: true
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  #
  # c8y settings
  C8Y_SETTINGS_CI: true
  C8Y_HOST: ${{ secrets.C8Y_HOST }}
  # Tenant name is optional
  # C8Y_TENANT: ${{ secrets.C8Y_TENANT }}
  C8Y_USERNAME: ${{ secrets.C8Y_USERNAME }}
  C8Y_PASSWORD: ${{ secrets.C8Y_PASSWORD }}
  KEEP_LAST: ${{ github.event.inputs.keep_last }}

on:
  workflow_dispatch:
    inputs:
      keep_last:
        description: 'Number of deployments to keep'
        required: false
        default: '5'

  release:
    types: [released]  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Manually download
          gh release download -R reubenmiller/go-c8y-cli --pattern c8y_linux_amd64 --dir "$HOME/.local/bin"
          mv "$HOME/.local/bin/c8y_linux_amd64" "$HOME/.local/bin/c8y"
          chmod +x "$HOME/.local/bin/c8y"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

          # Using homewbrew
          #brew tap reubenmiller/go-c8y-cli
          #brew update
          #brew install go-c8y-cli

      - name: Deploy web applications
        run: |
          chmod +x ./2022-01-27/02-cicd/deploy-webapps.sh
          ./2022-01-27/02-cicd/deploy-webapps.sh "$KEEP_LAST" < /dev/null

      - name: Deploy microservices
        if: ${{ True }}
        run: |
          cd ./2022-01-27/02-cicd
          c8y microservices create --file ./hello-world.zip --availability PRIVATE
        shell: bash
      
      - name: Deploy software
        run: |
          cd ./2022-01-27/02-cicd
          name=python3-c8ylp
          (c8y software get -n --id "$name" --silentStatusCodes 404 || c8y software create -n --name "$name") \
            | c8y software versions create --file "$name"*.deb
        shell: bash
      
      - name: Deploy configuration
        run: |
          cd ./2022-01-27/02-cicd
          ./deploy-config.sh < /dev/null
        shell: bash
